### ISSUE TITLE
Error- " Unable to open object (Object '19' doesn't exist)"

### ISSUE THREAD

**Issue by raikar008** [Lab41/Magnolia#89]
Hello, after creating the .h5 file from training data, when I apply siterator, This error is coming - "Unable to open object (Object '19 doesn't exist)"

The image of hdf5 is attached with this.

![screenshot from 2017-07-28 18-45-43](https://user-images.githubusercontent.com/26719772/28718913-99134bcc-73c5-11e7-84f0-45aaf5835c7f.png)

**Comment by raikar008** [comment]
I took only a small dataset to make sure first I learn what's happening in code. ( And to bring down computation complexity)

**Comment by karllab41** [comment]
Hello, thanks for using our repository, and sorry for the late response. It looks like this error comes about because the key that you're looking at (speaker '19' in your case) is not in the *.h5 file that you had created. If you can show us the error with the trace as well as your input data, then perhaps that could illuminate your problem a bit more...
